name: Auto Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-activities:
    runs-on: ubuntu-latest
    name: Update activities
    steps:
      - uses: actions/checkout@v3
      - uses: xhyrom/setup-bun@v0.1.5
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup NodeJS v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: 'Run script'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd scripts
          bun install
          bun run update:activities
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

  update-guilds:
    runs-on: ubuntu-latest
    name: Update guilds
    steps:
      - uses: actions/checkout@v3
      - uses: xhyrom/setup-bun@v0.1.5
        with:
          bun-version: latest
      - name: Setup NodeJS v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: 'Run script'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd scripts
          bun install
          bun run update:guilds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
